name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # Replace with your default branch name

permissions:
  id-token: write  # Required for GitHub Pages deployment
  contents: read   # Required to read the repository contents
  pages: write     # Required to deploy to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Ensures submodules are fetched and initialized
          fetch-depth: 0    # Fetch full history to support submodules


      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Required for Hugo Extended version

      - name: Build Hugo Site
        run: hugo --minify

      - name: Debug Hugo Output
        run: ls -la public  # Verify generated files in the output directory

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Ensure this matches the `publishDir` in your Hugo config

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}